version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.0
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
      - filehost:filehost
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.22.0
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  filehost:
    image: semtech/static-file-service:0.2.0
    volumes:
      - ./data/files/:/data
      - ./config/nginx:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
   image: semtech/mu-migrations-service:0.8.0
   volumes:
    - ./config/migrations:/data/migrations
   labels:
     - "logging=true"
   restart: always
   logging: *default-logging
